
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xerieptcfwofkbyfhrvw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlcmllcHRjZndvZmtieWZocnZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0ODE4NjgsImV4cCI6MjA2MjA1Nzg2OH0.4B7d-cnoZrmz6xw-fr_U7vW-ESfszXeuzPacl5to6p8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
